### ISSUE TITLE
Login Credentials not working

### ISSUE THREAD

**Issue by timschloe** [undp/carbon-registry#60]
So I finally managed to find the Password in the log file, but unfortunately...:
![image](https://user-images.githubusercontent.com/6918041/229757703-ba1d57a4-0045-4ff1-bb10-1a5507993566.png)
note that I have changed the country name in the docker-compose in at least 7 different positions, and the email is still using the wrong country name. Suggesting to make that a global variable of sorts.

but, unfortunately, on the login I get:

![image](https://user-images.githubusercontent.com/6918041/229757748-c71d30aa-873e-41e0-a618-6eb5b74edccf.png)

**Comment by palindaa** [comment]
@timschloe I think you gave your root email as `<timschloe@gmail.com>`. I used < and > to indicate it is configurable. So currently if you try to login with <timschloe@gmail.com> and mentioned password it will work.

**Comment by timschloe** [comment]
Please see screenshot. I'm using the email and password copy-pasted directly from the log.

**Comment by palindaa** [comment]
Please enter email as `<timschloe@gmail.com>` not timschloe@gmail.com, since that what you gave in the docker-compose file.

**Comment by timschloe** [comment]
[bashscript.txt](https://github.com/undp/carbon-registry/files/11147572/bashscript.txt)
[log.txt](https://github.com/undp/carbon-registry/files/11147574/log.txt)

You should be able to re-create the error on any Debian 11 fresh install.

**Comment by palindaa** [comment]
@timschloe  this is the issue. Since you gave root email as `rootEmail: <timschloe@gmail.com>`. Now you root account login email is `<timschloe@gmail.com>`. Not timschloe@gmail.com. So currently if you want to login to the system please enter 
email: `<timschloe@gmail.com>`
password: UgV0iq6Z

Please try with above credentials. 

If you want to recreate you root account for timschloe@gmail.com email, update docker compose file rootEmail: <timschloe@gmail.com> to rootEmail: timschloe@gmail.com and  drop the existing db volume. Use following command to to do that. `docker volume rm undp-carbon-registry_data`

**Comment by palindaa** [comment]
<img width="529" alt="Screenshot 2023-04-04 at 3 00 03 PM" src="https://user-images.githubusercontent.com/99331873/229775197-59e7bd2b-1f48-41bd-ab78-236306fcf684.png">

Please let me know above input worked on your system or not.

**Comment by palindaa** [comment]
![229757748-c71d30aa-873e-41e0-a618-6eb5b74edccf](https://user-images.githubusercontent.com/99331873/229775441-cace8366-304d-4549-a7a4-de77f65b3cf0.png)

Please let me know above input worked on your system or not

**Comment by palindaa** [comment]
@timschloe I tried same steps on a MacOS, I don't think it will be different from linux since we are using docker. Please refer following video

https://user-images.githubusercontent.com/99331873/230027723-686135c4-0daa-4796-ae5e-ae939877a09b.mp4


Root account create only on first docker-compose up. If you want to clean previous database and recreate root user again please execute following commands to remove volume.

1. View existing volumes - `docker volume ls`
2. Remove database volume - `docker volume rm carbon-registry_data` (This name can be different, this name valid based on your repo name)

**Comment by palindaa** [comment]
In your Debian 11 installation if you login to the db and check the user account passwords and emails you will able to find credentials sort out the issue. I assume initially you gave root email as `<timschloe@gmail.com>` so some kind of issue with that. 

Let me know if we can close this issue based on that.
